# Copyright (C) 2022 Obscurity Labs LLC. <admin@obscuritylabs.com> - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited.
# All rights reserved. No warranty, explicit or implicit, provided.
# Proprietary and confidential.

variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"
  PYPI_REGISTRY: https://gitlab.obscuritylabs.com/api/v4/projects/$CI_PROJECT_ID/packages/pypi

cache: &global-poetry-cache
  key:
    files:
      - $CI_PROJECT_DIR/darkmoon/poetry.lock
      - $CI_PROJECT_DIR/darkmoon/.gitlab-ci.yml
    prefix: poetry
  paths:
    - $CI_PROJECT_DIR/darkmoon/.venv

include:
  - local: templates/darkmoon.gitlab-ci.yml

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - changes:
        - darkmoon/*

stages:
  - quality
  - test

.quality-template: &quality
  extends: .install-deps-template
  image: python:3.10
  stage: quality
  cache:
    <<: *global-poetry-cache

# Code Quality Stage
check-lint:
  <<: *quality
  script:
    - make check-lint

check-format:
  <<: *quality
  script:
    - make check-format

check-types:
  <<: *quality
  script:
    - make check-types

check-imports:
  <<: *quality
  script:
    - make check-imports

# Testing Stage
python3.10:
  extends: .install-deps-template
  image: python:3.10
  stage: test
  script: make test
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
      - darkmoon/coverage.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    when: always
    expire_in: 1 week
  cache:
    <<: *global-poetry-cache
