version: "3"

services:
  darkmoon:
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      - MONGODB_CONN=mongodb://darkmoon:password@mongodb:27017/?authMechanism=DEFAULT
      - UVICORN_RELOAD=true
    volumes:
      - ./darkmoon:/opt/app/darkmoon/
  mongodb:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=darkmoon
      - MONGO_INITDB_ROOT_USERNAME=darkmoon
      - MONGO_INITDB_ROOT_PASSWORD=password

    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb:
  mongodb_config:
